# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a543c6ded9d57402664ea1d677dbee796585f1d1e9d23401f9971c60a36e702009f2ab9edbd0e3989bfeab6d6bef4ac0847f27bde718340dc5079370103dc310

test:
  secret_key_base: 512703241269df169b573ad684d9cd1702ddb7aa215872d4dc7da7d2a9b9dbf69e1c3a5b5e24332cc999c409c4d0b1b048f987291666aca2c225f627791ea08c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
